import { useEffect, useMemo, useState } from "react";
import { CheckCircle2, Mail, Search, Users } from "lucide-react";
import api from "@/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { useI18n } from "@/i18n";

export default function BulkAccountProvisioning({ type, onCancel, onCompleted }) {
  const { t } = useI18n();
  const familyMode = type === "family";
  const [rows, setRows] = useState([]), [selected, setSelected] = useState([]), [search, setSearch] = useState(""), [busy, setBusy] = useState(true), [error, setError] = useState(""), [result, setResult] = useState(null), [pendingBusy, setPendingBusy] = useState(false), [pendingResult, setPendingResult] = useState(null);
  const idKey = familyMode ? "family_id" : "player_id", nameKey = familyMode ? "family_name" : "player_name";
  const endpoint = `/account-provisioning/${familyMode ? "families" : "players"}`;
  useEffect(() => { setBusy(true); api.get(endpoint).then(({ data }) => setRows(data)).catch((e) => setError(e.response?.data?.detail || t("candidatesLoadError"))).finally(() => setBusy(false)); }, [endpoint, t]);
  const groupedRows = useMemo(() => familyMode ? Object.values(rows.reduce((groups, row) => { const id = row.family_id; const current = groups[id] || { ...row, emails: [], valid_email_count: 0 }; const emails = row.emails || (row.email ? [row.email] : []); current.emails = [...new Set([...current.emails, ...emails])]; current.valid_email_count = current.emails.length; groups[id] = current; return groups; }, {})) : rows, [rows, familyMode]);
  const visible = useMemo(() => groupedRows.filter((row) => `${row[nameKey]} ${(row.emails || [row.email || ""]).join(" ")}`.toLocaleLowerCase().includes(search.toLocaleLowerCase())), [groupedRows, search, nameKey]);
  const toggle = (id) => setSelected((all) => all.includes(id) ? all.filter((value) => value !== id) : [...all, id]);
  const submit = async () => { if (busy || !selected.length) return; setBusy(true); setError(""); try { const { data } = await api.post(`${endpoint}/invitations`, familyMode ? { family_ids: selected } : { player_ids: selected }); setResult(data); onCompleted?.(); } catch (e) { setError(e.response?.data?.detail || t("accountsCreateError")); } finally { setBusy(false); } };
  const resendPending = async () => { if (pendingBusy) return; setPendingBusy(true); setError(""); try { const { data } = await api.post("/account-provisioning/families/invitations/resend-pending", {}); setPendingResult(data); onCompleted?.(); } catch (e) { setError(e.response?.data?.detail || t("familyPendingResendError")); } finally { setPendingBusy(false); } };
  const selectVisible = () => setSelected((all) => { const ids = visible.map((row) => row[idKey]); return ids.every((id) => all.includes(id)) ? all.filter((id) => !ids.includes(id)) : Array.from(new Set(all.concat(ids))); });
  if (result) { const s = result.summary || {}; return <section className="space-y-4" data-testid="family-batch-result"><div className="rounded-2xl bg-emerald-50 p-5 text-emerald-950"><CheckCircle2 className="mb-2 h-8 w-8" /><h3 className="font-bold">Proceso completado</h3><dl className="mt-4 grid grid-cols-2 gap-2 text-center text-sm sm:grid-cols-4"><div><dt>Cuentas creadas</dt><dd className="text-lg font-bold">{s.accounts_created || 0}</dd></div><div><dt>Invitaciones enviadas</dt><dd className="text-lg font-bold">{s.invitations_sent || 0}</dd></div><div><dt>Accesos existentes</dt><dd className="text-lg font-bold">{s.existing_accesses || 0}</dd></div><div><dt>Familias a revisar</dt><dd className="text-lg font-bold">{s.families_for_review || 0}</dd></div></dl></div>{result.results?.length > 0 && <ul className="space-y-1 rounded-xl border border-slate-200 bg-white p-3 text-sm" aria-label="Detalle del resultado">{result.results.map((row) => <li key={(row.family_id || row.player_id) + "-" + (row.slot || "")}><strong>{row.family_id || row.player_id}</strong>: {row.reason || row.outcome || row.status}</li>)}</ul>}<Button type="button" onClick={onCancel}>{t("close")}</Button></section>; }
  return <section className="space-y-4"><div className="rounded-2xl bg-sky-50 p-4 text-sm text-sky-950"><strong>{familyMode ? "Crear accesos de familias seleccionadas" : t("bulkPlayerTitle")}</strong><p className="mt-1">La acción procesa todas las familias marcadas de una vez.</p></div>{familyMode && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><strong>{t("familyPendingResendTitle")}</strong><p className="mt-1 text-amber-900">{t("familyPendingResendDescription")}</p></div><Button type="button" variant="outline" disabled={pendingBusy} onClick={resendPending}>{pendingBusy ? t("sending") : t("familyPendingResendButton")}</Button></div>{pendingResult && <p className="mt-3 text-sm font-semibold text-amber-900">{t("familyPendingResendResult")} {pendingResult.sent || 0} · {pendingResult.pending || 0} · {pendingResult.failed || 0}</p>}</div>}<div className="flex gap-2"><label className="relative flex-1"><span className="sr-only">{t("search")}</span><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder={t("searchNameEmail")} /></label><Button type="button" variant="outline" onClick={selectVisible}>{t("selectAllAvailable")}</Button></div>{busy && !rows.length ? <p>Cargando…</p> : error ? <p role="alert">{error}</p> : <div className="max-h-80 space-y-2 overflow-y-auto">{visible.map((row) => <label key={row[idKey]} className="flex gap-3 rounded-xl border p-3"><input type="checkbox" checked={selected.includes(row[idKey])} onChange={() => toggle(row[idKey])} /><span><strong className="block">{row[nameKey]}</strong><small>{familyMode ? `${row.valid_email_count || 0} correo${row.valid_email_count === 1 ? " válido" : "s válidos"}` : (row.email || "Sin correo")}</small></span></label>)}</div>}<div className="flex justify-between"><Button type="button" variant="outline" onClick={onCancel}>{t("cancel")}</Button><Button type="button" disabled={busy || !selected.length} onClick={submit}><Users className="h-4 w-4" />Crear accesos ({selected.length}{familyMode ? " familias" : ""})</Button></div></section>;
}
