import React from "react";
import LegalDocument from "./LegalDocument";

const sections = [
  { id: "objeto", title: "Objeto, alcance y personas a las que se aplica", content: <><p>Esta Política de Privacidad explica cómo se tratan los datos personales en la plataforma Ikastxiki (Ikas-Txiki Manager), alojada en infraestructura asociada a <strong>ikasfutbase.cibermedida.es</strong>. Se dirige a familias, deportistas, menores de edad, personal de entidades deportivas y demás personas usuarias cuyos datos se incorporen a la plataforma.</p><p>Se aplica al uso de las áreas públicas y autenticadas de Ikastxiki, incluidas la creación y administración de cuentas, las funciones deportivas y organizativas, las comunicaciones de servicio y la atención de solicitudes relacionadas con la plataforma.</p></> },
  { id: "responsable", title: "Identidad y contacto del responsable", content: <><p><strong>Responsable del tratamiento:</strong> Francisco Javier Flor González, Cibermedida.<br /><strong>NIF:</strong> 30602373E.<br /><strong>Domicilio:</strong> Urbanización La Sorrozuela 114, 39170 Ajo, Cantabria.<br /><strong>Canal de privacidad:</strong> <a href="mailto:jfloradmin@cibermedida.es">jfloradmin@cibermedida.es</a>.</p><p>No se ha designado delegado de protección de datos. Para cuestiones sobre privacidad o para ejercer derechos, utilice el canal indicado.</p></> },
  { id: "categorias", title: "Categorías de datos tratados", content: <><p>Según la función utilizada y el perfil de la persona, Ikastxiki puede tratar las siguientes categorías:</p><ul><li>datos identificativos y de contacto, como nombre, apellidos, usuario, correo electrónico, teléfono o datos equivalentes facilitados para la gestión;</li><li>datos de acceso y credenciales, incluidos los necesarios para autenticar una cuenta y gestionar sesiones;</li><li>datos deportivos y organizativos, como equipo, convocatorias, entrenamientos, partidos, disponibilidad, estadísticas o información relacionada;</li><li>datos de ubicación vinculados a actividades, instalaciones, campos o eventos cuando sean necesarios para la organización;</li><li>datos de salud que se incorporen para una necesidad concreta de gestión deportiva o seguridad;</li><li>datos técnicos, registros de seguridad y de uso de la aplicación necesarios para su funcionamiento, trazabilidad, soporte y protección.</li></ul></> },
  { id: "origen", title: "Origen de los datos", content: <p>Los datos pueden proceder de la propia persona usuaria, de sus familias o representantes legales, de la entidad deportiva o de personal autorizado por esta, según la relación existente y la función de Ikastxiki utilizada. Quien incorpore información de otra persona debe estar legitimado para ello y aportar información exacta y actualizada.</p> },
  { id: "finalidades", title: "Finalidades del tratamiento", content: <ul><li>crear, activar y gestionar cuentas y accesos;</li><li>prestar las funciones deportivas y organizativas de la plataforma;</li><li>gestionar equipos, jugadores, familias, calendario, convocatorias y comunicaciones de servicio;</li><li>proteger las cuentas, prevenir accesos no autorizados y atender incidencias de seguridad;</li><li>prestar soporte y responder consultas;</li><li>cumplir las obligaciones legales aplicables.</li></ul> },
  { id: "base-juridica", title: "Base jurídica", content: <><p>La base jurídica depende de la finalidad y del dato concreto:</p><ul><li><strong>Relación de servicio:</strong> para los datos ordinarios necesarios para crear y administrar cuentas y prestar las funciones solicitadas.</li><li><strong>Consentimiento:</strong> cuando la normativa o la función concreta lo requiera y sea posible prestarlo libremente.</li><li><strong>Consentimiento explícito y separado:</strong> para los datos de salud cuando corresponda. La plataforma debe recoger y registrar ese consentimiento antes de habilitar un tratamiento que lo exija.</li><li><strong>Interés legítimo:</strong> de manera limitada para seguridad, prevención del fraude, protección de cuentas y defensa ante reclamaciones, tras valorar que no prevalezcan los derechos de las personas afectadas.</li><li><strong>Obligación legal:</strong> cuando proceda por una norma aplicable.</li></ul></> },
  { id: "salud", title: "Datos de salud", content: <><p>Los datos de salud son categorías especiales de datos. Solo deben solicitarse o incorporarse cuando sean necesarios para una función concreta, proporcional y vinculada a la actividad. Cuando la base jurídica sea el consentimiento, este debe ser <strong>explícito, separado e informado</strong>.</p><p>Estos datos no se utilizarán para fines comerciales, publicitarios ni incompatibles con la finalidad para la que se recogieron. La revisión técnica realizada no acredita actualmente un flujo separado de recogida y registro de consentimiento explícito para datos de salud; este control debe implantarse y documentarse antes de ampliar o normalizar dicho tratamiento.</p></> },
  { id: "menores", title: "Protección reforzada de menores", content: <><p>La privacidad de niños, niñas y adolescentes requiere especial cuidado. Ikastxiki no debe utilizar datos de menores para publicidad ni para perfiles comerciales. La información sobre menores debe limitarse a la necesaria para la gestión deportiva y organizativa autorizada.</p><p>Cuando el tratamiento se base en el consentimiento, para menores de 14 años este debe ser prestado o autorizado por padre, madre o tutor legal. La persona adulta responsable debe mantener actualizados sus datos de contacto y las autorizaciones que correspondan.</p><p>La revisión técnica no acredita un control automático de autorización parental o de edad para menores de 14 años. Hasta que se implante una comprobación y un registro verificable, la entidad responsable debe gestionar esa validación por un procedimiento separado y documentado.</p></> },
  { id: "destinatarios", title: "Destinatarios y encargados del tratamiento", content: <><p>Los datos no se venden. Pueden acceder a ellos, únicamente cuando sea necesario para prestar el servicio y bajo instrucciones del responsable, categorías de proveedores vinculadas al alojamiento de la infraestructura, correo transaccional configurado, soporte y copias de seguridad. El acceso de cada categoría debe formalizarse y limitarse conforme a la normativa aplicable.</p><p>No se identifican en esta Política proveedores concretos porque no se ha verificado un inventario contractual y de configuración actualizado de todos ellos.</p></> },
  { id: "transferencias", title: "Transferencias internacionales", content: <p>En la revisión del código y de la información de infraestructura disponible no se ha identificado ni documentado un inventario que confirme la ubicación de todos los proveedores configurados. Por ello, esta Política no afirma que no existan transferencias internacionales. El responsable debe verificarlo antes de publicar una declaración definitiva y, si las hubiera, informar de las garantías aplicables.</p> },
  { id: "conservacion", title: "Conservación, bloqueo y eliminación", content: <p>Los datos se conservan mientras la cuenta y la gestión de la aplicación permanezcan activas. Tras la baja o el traslado, se bloquearán únicamente durante los plazos legales de responsabilidad que correspondan y, finalizados estos, se eliminarán. Pueden conservarse registros mínimos cuando sean imprescindibles para acreditar una actuación, atender una incidencia o cumplir una obligación legal durante el plazo aplicable.</p> },
  { id: "seguridad", title: "Medidas organizativas y técnicas", content: <p>Ikastxiki aplica medidas organizativas y técnicas adecuadas al riesgo, sin que ello elimine por completo cualquier posibilidad de incidencia. Entre ellas se encuentran controles de acceso y permisos, gestión de credenciales y sesiones, medidas de protección frente a accesos no autorizados, registros para seguridad y trazabilidad, y procedimientos de soporte y copias de seguridad conforme a la configuración del servicio. No se publican detalles que puedan debilitar la seguridad.</p> },
  { id: "automatizacion", title: "Decisiones automatizadas y perfiles", content: <p>La revisión del código no ha identificado decisiones basadas únicamente en tratamiento automatizado que produzcan efectos jurídicos o afecten de manera similar y significativa a una persona. Existen funciones de apoyo, como avisos o sugerencias de revisión en procesos organizativos, que no sustituyen la decisión humana responsable. Si se incorporara una decisión automatizada relevante, se informaría previamente de su lógica, alcance y garantías.</p> },
  { id: "derechos", title: "Derechos de las personas", content: <p>Puede solicitar acceso a sus datos, rectificación de los inexactos, supresión cuando proceda, oposición, limitación del tratamiento, portabilidad y retirada del consentimiento en cualquier momento, sin afectar a la licitud del tratamiento previo. Estos derechos se ejercen dentro de los límites y condiciones previstos por la normativa aplicable.</p> },
  { id: "ejercicio", title: "Cómo ejercer sus derechos", content: <p>Escriba a <a href="mailto:jfloradmin@cibermedida.es">jfloradmin@cibermedida.es</a>, indicando el derecho que desea ejercer y los datos necesarios para localizar la cuenta o la información afectada. Podrá solicitarse una identificación razonable cuando sea necesaria para proteger los datos y confirmar la identidad de quien realiza la petición.</p> },
  { id: "reclamacion", title: "Reclamación ante la autoridad de control", content: <p>Si considera que el tratamiento no se ajusta a la normativa, puede presentar una reclamación ante la Agencia Española de Protección de Datos (AEPD). Consulte sus canales actualizados en <a href="https://www.aepd.es" target="_blank" rel="noreferrer">www.aepd.es</a>.</p> },
  { id: "cambios", title: "Cambios en esta Política", content: <p>Esta Política puede actualizarse para reflejar cambios normativos, organizativos o funcionales. La fecha de última actualización figura al inicio. Cuando un cambio sea relevante, se adoptarán las medidas de información que correspondan antes de aplicar el nuevo tratamiento.</p> },
];

export default function PrivacyPolicy() { return <LegalDocument title="Política de Privacidad" lead="Información clara sobre el tratamiento de datos personales en Ikastxiki." sections={sections} />; }
