import React from "react";
import { Link } from "react-router-dom";
import LegalDocument from "./LegalDocument";

const sections = [
  { id: "titular", title: "Identificación del titular", content: <p>La plataforma Ikastxiki (Ikas-Txiki Manager) es titularidad de <strong>Francisco Javier Flor González, Cibermedida</strong>, NIF 30602373E, con domicilio en Urbanización La Sorrozuela 114, 39170 Ajo, Cantabria. Para asuntos de privacidad: <a href="mailto:jfloradmin@cibermedida.es">jfloradmin@cibermedida.es</a>.</p> },
  { id: "objeto", title: "Objeto y aceptación", content: <p>Estas Condiciones regulan el acceso y uso de Ikastxiki como plataforma de gestión y comunicación deportiva. Al registrarse, acceder o utilizar sus funciones, la persona usuaria acepta estas Condiciones y se compromete a cumplir la normativa aplicable. Si no está de acuerdo, debe abstenerse de utilizar la plataforma.</p> },
  { id: "registro", title: "Personas usuarias, registro y veracidad", content: <p>Las cuentas se asignan o se crean conforme a la organización de la entidad deportiva. Cada persona debe facilitar datos veraces, completos y actualizados, y comunicar las correcciones necesarias. No se permite crear cuentas con datos de terceros sin autorización o emplear la plataforma para fines ajenos a la gestión autorizada.</p> },
  { id: "menores", title: "Cuentas de menores", content: <p>Las cuentas y datos de menores deben gestionarse bajo la responsabilidad de sus padres, madres o representantes legales y de la entidad deportiva que corresponda. La persona adulta responsable debe conservar actualizados los datos de contacto y autorizaciones necesarios. Cuando la ley exija consentimiento del representante legal, debe obtenerse antes del tratamiento basado en él.</p> },
  { id: "credenciales", title: "Credenciales, contraseñas y sesiones", content: <p>Las credenciales son personales y confidenciales. La persona usuaria debe elegir una contraseña segura, no compartirla, cerrar la sesión cuando proceda y comunicar sin demora cualquier sospecha de uso indebido. Ikastxiki puede adoptar medidas de seguridad como la caducidad de enlaces de recuperación, invalidación de sesiones o restablecimiento de acceso cuando resulte necesario.</p> },
  { id: "uso", title: "Uso permitido", content: <p>Ikastxiki se utiliza para la gestión y comunicación deportiva: equipos, jugadores, familias, actividades, calendario, convocatorias, información organizativa y acceso al área personal. El uso debe ser respetuoso, diligente y coherente con las instrucciones de la entidad deportiva y estas Condiciones.</p> },
  { id: "prohibiciones", title: "Usos prohibidos", content: <ul><li>acceder o intentar acceder a cuentas, datos o sistemas sin autorización;</li><li>suplantar identidades o compartir credenciales;</li><li>extraer masivamente datos o emplear automatismos no autorizados;</li><li>difundir datos personales, imágenes o información deportiva sin base legítima;</li><li>acosar, discriminar, amenazar o publicar contenido ilícito;</li><li>vulnerar la privacidad, la seguridad, los derechos de terceros o la normativa aplicable.</li></ul> },
  { id: "datos-sensibles", title: "Datos deportivos, de salud y ubicación", content: <p>Los datos deportivos, de salud y ubicación requieren especial prudencia. Solo deben incorporarse cuando sean necesarios para la finalidad autorizada y por personas habilitadas. Los datos de salud no pueden destinarse a publicidad, fines comerciales ni usos incompatibles. Quien acceda a esta información debe respetar la confidencialidad y las instrucciones de la entidad responsable.</p> },
  { id: "salud", title: "No sustituye atención médica ni seguridad", content: <p>Ikastxiki no sustituye la atención médica, los servicios de emergencia, las decisiones clínicas ni los protocolos de seguridad de clubes o entidades. Ante una urgencia debe acudirse a los servicios de emergencia y a los profesionales competentes. La información incluida en la plataforma no debe utilizarse como diagnóstico, indicación clínica o sustituto de protocolos deportivos y de protección.</p> },
  { id: "disponibilidad", title: "Disponibilidad, mantenimiento y actualizaciones", content: <p>El servicio puede requerir mantenimiento, actualizaciones, medidas de seguridad o interrupciones razonables. Se procurará reducir su impacto cuando sea posible, pero no se garantiza disponibilidad ininterrumpida ni ausencia total de errores. Las personas usuarias deben mantener medios alternativos razonables para actividades críticas de la entidad.</p> },
  { id: "soporte", title: "Soporte y comunicaciones de servicio", content: <p>Ikastxiki puede utilizar los datos de contacto disponibles para comunicaciones necesarias sobre acceso, seguridad, incidencias, cambios operativos o soporte. Las comunicaciones deportivas y organizativas deben enviarse únicamente por personas autorizadas y conforme a las preferencias, permisos y base jurídica que correspondan.</p> },
  { id: "suspension", title: "Suspensión, cancelación y eliminación", content: <p>Podrá suspenderse, limitarse o cancelarse una cuenta ante un incumplimiento, riesgo de seguridad, solicitud de la entidad autorizada o finalización de la relación de servicio. Estas medidas se aplicarán de forma proporcionada y sin perjuicio de los derechos legales de las personas afectadas. La eliminación de datos se regirá por la <Link to="/privacidad">Política de Privacidad</Link>.</p> },
  { id: "propiedad", title: "Propiedad intelectual", content: <p>El software, el logotipo, el diseño, las marcas y los contenidos propios de Ikastxiki están protegidos por la normativa aplicable. No se concede licencia distinta de la necesaria para utilizar la plataforma conforme a estas Condiciones. Los contenidos aportados por personas usuarias siguen sujetos a los derechos de sus titulares y a las autorizaciones necesarias.</p> },
  { id: "responsabilidad", title: "Responsabilidad y límites", content: <p>Cada persona usuaria responde de su uso de la plataforma, de la licitud de la información que introduce y de los daños que cause por incumplir estas Condiciones o la normativa. En la medida permitida por la ley, Ikastxiki no responde de daños derivados de un uso indebido, de información aportada por terceros o de indisponibilidades ajenas a un control razonable. Nada de lo anterior excluye derechos irrenunciables ni responsabilidades que no puedan limitarse legalmente.</p> },
  { id: "enlaces", title: "Enlaces a terceros", content: <p>Si alguna función incorpora enlaces a sitios o servicios de terceros, estos se rigen por sus propias condiciones y políticas. Ikastxiki no controla su contenido, disponibilidad ni tratamiento de datos, salvo que se indique expresamente lo contrario.</p> },
  { id: "privacidad", title: "Protección de datos", content: <p>El tratamiento de datos personales se explica de forma destacada en la <Link to="/privacidad">Política de Privacidad de Ikastxiki</Link>, que forma parte de la información esencial para utilizar la plataforma.</p> },
  { id: "vigencia", title: "Modificación, vigencia, nulidad y normativa", content: <p>Estas Condiciones pueden modificarse por cambios normativos, de seguridad, organizativos o funcionales. La versión vigente será la publicada con su fecha de actualización. Si una cláusula fuera inválida, las restantes conservarán su eficacia. Se aplica la legislación española y, cuando proceda, la jurisdicción que determine la normativa aplicable, respetando especialmente los fueros y derechos de consumidores y usuarios.</p> },
];

export default function TermsOfUse() { return <LegalDocument title="Condiciones de Uso" lead="Reglas claras para un uso seguro, respetuoso y responsable de Ikastxiki." sections={sections} />; }
